//! The service definitions every Warehouse route is generated from.
//!
//! Both sides of the wire are built from these traits: the server implements them, the
//! SDK in [`crate::sdk`] calls them, and the OpenAPI document is derived from them. A
//! route cannot drift between server, client and documentation because there is only one
//! declaration of it.

use crate::service::catalog::{CatalogService, CatalogServiceClientImpl, CatalogServiceURL};
use crate::service::system::{SystemService, SystemServiceClientImpl, SystemServiceURL};

pub(crate) use zelus::define_path_variable;
pub(crate) use zelus::error::{define_error, error};

pub use zelus::framework_router;
pub use zelus::sdk::ZelusClientImpl;

pub mod catalog;
pub mod system;

define_error!(auth {
    invalid("Authentication is invalid" UNAUTHORIZED),
});

define_error!(catalog {
    not_found("This instance does not serve that catalog" NOT_FOUND),
    unavailable("That catalog has not been resolved yet" SERVICE_UNAVAILABLE),
});

define_path_variable!(catalog "The catalog id");
define_path_variable!(runtime "The language runtime catalog id");

error!(BlankError, auth::invalid);

/// Every service a Warehouse instance serves.
pub trait WarehouseServices: CatalogService + SystemService {}

/// Every service the SDK can call.
pub trait WarehouseServicesClientImpl: CatalogServiceClientImpl + SystemServiceClientImpl {}

/// URL construction for every service.
pub trait WarehouseServicesURL: WarehouseServices + CatalogServiceURL + SystemServiceURL {}

/// Builds the `OpenAPI` document describing every route an instance serves.
///
/// Derived from the service definitions rather than from a running server, so it can be
/// generated by anything that has this crate — including a docs build in CI.
#[must_use]
pub fn api_document<T>(instance: &T) -> utoipa::openapi::OpenApi
where
    T: WarehouseServices + Clone + Send + Sync + Sized + 'static,
{
    use utoipa::OpenApi as _;

    #[derive(utoipa::OpenApi)]
    #[openapi()]
    struct ApiDoc;

    let (with_auth, without_auth) = framework_router!(T instance (with_auth,without_auth,) {
        CatalogService, SystemService
    });

    let (_router, api) = utoipa_axum::router::OpenApiRouter::with_openapi(ApiDoc::openapi())
        .merge(with_auth.into_openapi())
        .merge(without_auth.into_openapi())
        .split_for_parts();

    api
}
